import pandas as pd

data = [
    {"item_name": "apple", "category": "Fruits & Vegetables"},
    {"item_name": "banana", "category": "Fruits & Vegetables"},
    {"item_name": "orange", "category": "Fruits & Vegetables"},
    {"item_name": "grapes", "category": "Fruits & Vegetables"},
    {"item_name": "strawberries", "category": "Fruits & Vegetables"},
    {"item_name": "blueberries", "category": "Fruits & Vegetables"},
    {"item_name": "pear", "category": "Fruits & Vegetables"},
    {"item_name": "peach", "category": "Fruits & Vegetables"},
    {"item_name": "melon", "category": "Fruits & Vegetables"},
    {"item_name": "pineapple", "category": "Fruits & Vegetables"},
    {"item_name": "mango", "category": "Fruits & Vegetables"},
    {"item_name": "kiwi", "category": "Fruits & Vegetables"},
    {"item_name": "spinach", "category": "Fruits & Vegetables"},
    {"item_name": "broccoli", "category": "Fruits & Vegetables"},
    {"item_name": "carrot", "category": "Fruits & Vegetables"},
    {"item_name": "lettuce", "category": "Fruits & Vegetables"},
    {"item_name": "cucumber", "category": "Fruits & Vegetables"},
    {"item_name": "tomato", "category": "Fruits & Vegetables"},
    {"item_name": "onion", "category": "Fruits & Vegetables"},
    {"item_name": "garlic", "category": "Fruits & Vegetables"},
    {"item_name": "pepper", "category": "Fruits & Vegetables"},
    {"item_name": "courgette", "category": "Fruits & Vegetables"},
    {"item_name": "aubergine", "category": "Fruits & Vegetables"},
    {"item_name": "potato", "category": "Fruits & Vegetables"},
    {"item_name": "sweet potato", "category": "Fruits & Vegetables"},

    {"item_name": "milk", "category": "Eggs & Dairy"},
    {"item_name": "whole milk", "category": "Eggs & Dairy"},
    {"item_name": "semi skimmed milk", "category": "Eggs & Dairy"},
    {"item_name": "egg", "category": "Eggs & Dairy"},
    {"item_name": "eggs", "category": "Eggs & Dairy"},
    {"item_name": "yogurt", "category": "Eggs & Dairy"},
    {"item_name": "greek yogurt", "category": "Eggs & Dairy"},
    {"item_name": "butter", "category": "Eggs & Dairy"},
    {"item_name": "cheddar", "category": "Eggs & Dairy"},
    {"item_name": "mozzarella", "category": "Eggs & Dairy"},
    {"item_name": "parmesan", "category": "Eggs & Dairy"},
    {"item_name": "feta", "category": "Eggs & Dairy"},
    {"item_name": "cream cheese", "category": "Eggs & Dairy"},
    {"item_name": "double cream", "category": "Eggs & Dairy"},
    {"item_name": "single cream", "category": "Eggs & Dairy"},
    {"item_name": "cottage cheese", "category": "Eggs & Dairy"},
    {"item_name": "sour cream", "category": "Eggs & Dairy"},
    {"item_name": "custard", "category": "Eggs & Dairy"},

    {"item_name": "bread", "category": "Bakery"},
    {"item_name": "bagel", "category": "Bakery"},
    {"item_name": "croissant", "category": "Bakery"},
    {"item_name": "muffin", "category": "Bakery"},
    {"item_name": "brioche", "category": "Bakery"},
    {"item_name": "wrap", "category": "Bakery"},
    {"item_name": "pitta bread", "category": "Bakery"},
    {"item_name": "naan bread", "category": "Bakery"},
    {"item_name": "tortilla", "category": "Bakery"},
    {"item_name": "burger buns", "category": "Bakery"},
    {"item_name": "hot dog buns", "category": "Bakery"},
    {"item_name": "sourdough", "category": "Bakery"},
    {"item_name": "crumpets", "category": "Bakery"},
    {"item_name": "pancakes", "category": "Bakery"},
    {"item_name": "waffles", "category": "Bakery"},

    {"item_name": "pasta", "category": "Pantry"},
    {"item_name": "spaghetti", "category": "Pantry"},
    {"item_name": "penne", "category": "Pantry"},
    {"item_name": "rice", "category": "Pantry"},
    {"item_name": "basmati rice", "category": "Pantry"},
    {"item_name": "olive oil", "category": "Pantry"},
    {"item_name": "canned tomatoes", "category": "Pantry"},
    {"item_name": "beans", "category": "Pantry"},
    {"item_name": "kidney beans", "category": "Pantry"},
    {"item_name": "chickpeas", "category": "Pantry"},
    {"item_name": "lentils", "category": "Pantry"},
    {"item_name": "flour", "category": "Pantry"},
    {"item_name": "sugar", "category": "Pantry"},
    {"item_name": "salt", "category": "Pantry"},
    {"item_name": "black pepper", "category": "Pantry"},
    {"item_name": "vinegar", "category": "Pantry"},
    {"item_name": "soy sauce", "category": "Pantry"},
    {"item_name": "stock cubes", "category": "Pantry"},
    {"item_name": "peanut butter", "category": "Pantry"},
    {"item_name": "jam", "category": "Pantry"},
    {"item_name": "honey", "category": "Pantry"},
    {"item_name": "oats", "category": "Pantry"},
    {"item_name": "cereal", "category": "Pantry"},
    {"item_name": "tuna", "category": "Pantry"},

    {"item_name": "water", "category": "Drinks"},
    {"item_name": "sparkling water", "category": "Drinks"},
    {"item_name": "orange juice", "category": "Drinks"},
    {"item_name": "apple juice", "category": "Drinks"},
    {"item_name": "cola", "category": "Drinks"},
    {"item_name": "lemonade", "category": "Drinks"},
    {"item_name": "coffee", "category": "Drinks"},
    {"item_name": "tea", "category": "Drinks"},
    {"item_name": "green tea", "category": "Drinks"},
    {"item_name": "iced tea", "category": "Drinks"},
    {"item_name": "smoothie", "category": "Drinks"},
    {"item_name": "protein shake", "category": "Drinks"},
    {"item_name": "coconut water", "category": "Drinks"},
    {"item_name": "hot chocolate", "category": "Drinks"},
    {"item_name": "energy drink", "category": "Drinks"},
]

df = pd.DataFrame(data)
df.to_csv("data/processed/grocery_categories.csv", index=False)

print(df.head())
print(f"\nTotal rows: {len(df)}")
print("\nSaved to data/processed/grocery_categories.csv")